#!/usr/bin/env bash
# develop-daemon.sh — generated by /develop --loop=daemon
#
# Iterates the ticket queue at {{queue_path}}, spawning one Claude session per
# ticket via `{{claude_cmd}} /develop <ticket-id> {{develop_args}}`. Exits when
# the queue is empty OR after N tickets, whichever comes first.
#
# Variables (substituted at install time):
#   {{feature_id}}     feature id this daemon belongs to
#   {{queue_path}}     absolute path to .develop-queue.json
#   {{claude_cmd}}     `claude` (or absolute path)
#   {{develop_args}}   extra flags to forward verbatim (e.g. --dry-run)
#
# Usage:
#   bash develop-daemon.sh -n 5      # process up to 5 tickets
#   bash develop-daemon.sh           # default -n 1 (single ticket)
#   bash develop-daemon.sh --status  # print queue + processed counts and exit

set -euo pipefail

FEATURE_ID="{{feature_id}}"
QUEUE="{{queue_path}}"
CLAUDE_CMD="{{claude_cmd}}"
DEVELOP_ARGS="{{develop_args}}"
N=1

while [ $# -gt 0 ]; do
  case "$1" in
    -n) N="$2"; shift 2 ;;
    -n*) N="${1#-n}"; shift ;;
    --status)
      jq '{queue_size: (.queue | length), processed: (.processed | length), feature_id: "'"$FEATURE_ID"'"}' "$QUEUE"
      exit 0
      ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

[ -f "$QUEUE" ] || { echo "ERROR: queue not found: $QUEUE" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq required" >&2; exit 1; }
command -v "$CLAUDE_CMD" >/dev/null 2>&1 || { echo "ERROR: $CLAUDE_CMD not on PATH" >&2; exit 1; }

processed=0
while [ "$processed" -lt "$N" ]; do
  next=$(jq -r '.queue[0] // empty' "$QUEUE")
  if [ -z "$next" ]; then
    echo "queue empty — done"
    exit 0
  fi

  echo "=== ticket: $next ($(($processed + 1))/$N) ==="
  if "$CLAUDE_CMD" /develop "$next" $DEVELOP_ARGS; then
    echo "ok: $next"
  else
    rc=$?
    echo "fail: $next (rc=$rc) — daemon stops" >&2
    exit "$rc"
  fi
  processed=$((processed + 1))
done

echo "processed $processed ticket(s); $(jq '.queue | length' "$QUEUE") remaining"
